version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    environment:
      APP_ENV: ${APP_ENV:-dev}
    tty: true
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    environment:
      SERVER_NAME: ${SERVER_NAME}
    volumes:
      - ./.docker/nginx/templates:/etc/nginx/templates
      - ./:/srv/app
    ports:
      - "80:80"
    depends_on:
      - php